"""Escritura determinista del script Blender, sin importar bpy en el proceso principal."""

from __future__ import annotations

import json
from pathlib import Path


def write_rebuild_script(destination: Path, source_glb: Path, uv_manifest: Path) -> Path:
    """Genera un script idempotente que importa el GLB y aplica recortes declarados."""
    source = str(source_glb.resolve())
    manifest = str(uv_manifest.resolve())
    script = _SCRIPT_TEMPLATE.replace("__SOURCE_GLB__", json.dumps(source)).replace(
        "__UV_MANIFEST__", json.dumps(manifest)
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(script, encoding="utf-8")
    return destination


def write_object_rebuild_script(destination: Path, source_glb: Path, object_manifest: Path) -> Path:
    """Escribe un script Blender que conserva nodos GLB y les asigna atlas editables."""
    source = str(source_glb.resolve())
    manifest = str(object_manifest.resolve())
    script = _object_script(source, manifest, None, None, separate_loose_parts=False)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(script, encoding="utf-8")
    return destination


def write_single_object_rebuild_script(
    destination: Path, source_glb: Path, object_manifest: Path, object_id: str
) -> Path:
    """Escribe un script que importa sólo un nodo editable del manifiesto de objetos."""
    script = _object_script(
        str(source_glb.resolve()), str(object_manifest.resolve()), object_id, None, separate_loose_parts=False
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(script, encoding="utf-8")
    return destination


def write_atlas_rebuild_script(
    destination: Path,
    source_glb: Path,
    object_manifest: Path,
    atlas_path: Path,
    *,
    separate_loose_parts: bool = True,
) -> Path:
    """Escribe un script que conserva todos los nodos asociados a un atlas externo."""
    script = _object_script(
        str(source_glb.resolve()),
        str(object_manifest.resolve()),
        None,
        str(atlas_path.resolve()),
        separate_loose_parts=separate_loose_parts,
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(script, encoding="utf-8")
    return destination


def write_semantic_objects_rebuild_script(destination: Path, source_glb: Path, semantic_manifest: Path) -> Path:
    """Escribe un script que conserva componentes sueltos bajo padres semánticos."""
    script = _SEMANTIC_OBJECTS_SCRIPT_TEMPLATE.replace("__SOURCE_GLB__", json.dumps(str(source_glb.resolve()))).replace(
        "__SEMANTIC_MANIFEST__", json.dumps(str(semantic_manifest.resolve()))
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(script, encoding="utf-8")
    return destination


def _object_script(
    source: str, manifest: str, object_id: str | None, atlas_path: str | None, *, separate_loose_parts: bool
) -> str:
    target = "None" if object_id is None else json.dumps(object_id)
    target_atlas = "None" if atlas_path is None else json.dumps(atlas_path)
    return (
        _OBJECT_SCRIPT_TEMPLATE.replace("__SOURCE_GLB__", json.dumps(source))
        .replace("__OBJECT_MANIFEST__", json.dumps(manifest))
        .replace("__TARGET_OBJECT_ID__", target)
        .replace("__TARGET_ATLAS_PATH__", target_atlas)
        .replace("__SEPARATE_LOOSE_PARTS__", "True" if separate_loose_parts else "False")
    )


_OBJECT_SCRIPT_TEMPLATE = """# ruff: noqa
# Generated by atlas-splitter. Requires only Blender's built-in bpy API.
import json
from pathlib import Path

import bpy

SOURCE_GLB = __SOURCE_GLB__
OBJECT_MANIFEST = __OBJECT_MANIFEST__
TARGET_OBJECT_ID = __TARGET_OBJECT_ID__
TARGET_ATLAS_PATH = __TARGET_ATLAS_PATH__
SEPARATE_LOOSE_PARTS = __SEPARATE_LOOSE_PARTS__
ROOT_COLLECTION = "AtlasSplitterEditable"


def local_path(path):
    if path.startswith("/mnt/") and len(path) > 6:
        return path[5].upper() + ":\\\\" + path[7:].replace("/", "\\\\")
    return path


def material_from_atlas(name, atlas_path, flip_v):
    material = bpy.data.materials.new(name)
    material.use_nodes = True
    nodes, links = material.node_tree.nodes, material.node_tree.links
    principled = next(node for node in nodes if node.type == "BSDF_PRINCIPLED")
    texture = nodes.new("ShaderNodeTexImage")
    texture.image = bpy.data.images.load(local_path(atlas_path), check_existing=True)
    if flip_v:
        texcoord = nodes.new("ShaderNodeTexCoord")
        mapping = nodes.new("ShaderNodeMapping")
        mapping.inputs["Scale"].default_value[1] = -1.0
        mapping.inputs["Location"].default_value[1] = 1.0
        links.new(texcoord.outputs["UV"], mapping.inputs["Vector"])
        links.new(mapping.outputs["Vector"], texture.inputs["Vector"])
    links.new(texture.outputs["Color"], principled.inputs["Base Color"])
    return material


def separate_loose_parts(objects):
    for obj in objects:
        if obj.type != "MESH":
            continue
        base_name = obj.name
        bpy.ops.object.select_all(action="DESELECT")
        obj.select_set(True)
        bpy.context.view_layer.objects.active = obj
        bpy.ops.object.mode_set(mode="EDIT")
        bpy.ops.mesh.separate(type="LOOSE")
        bpy.ops.object.mode_set(mode="OBJECT")
        for index, part in enumerate(sorted(bpy.context.selected_objects, key=lambda item: item.name), start=1):
            part.name = f"{base_name}_part_{index:03d}"


def main():
    data = json.loads(Path(local_path(OBJECT_MANIFEST)).read_text(encoding="utf-8"))
    before = {obj.name for obj in bpy.context.scene.objects}
    bpy.ops.import_scene.gltf(filepath=local_path(SOURCE_GLB))
    imported = {obj.name: obj for obj in bpy.context.scene.objects if obj.name not in before}
    selected = [
        item for item in data["objects"]
        if (TARGET_OBJECT_ID is None or item["object_id"] == TARGET_OBJECT_ID)
        and (
            TARGET_ATLAS_PATH is None
            or TARGET_ATLAS_PATH in item.get("atlas_paths", [item["atlas_path"]])
        )
    ]
    for item in selected:
        obj = imported.get(item["node_name"])
        if obj is None or obj.type != "MESH":
            print("atlas-splitter: no se encontró nodo", item["node_name"])
            continue
        atlas_paths = item.get("atlas_paths", [item["atlas_path"]])
        if len(atlas_paths) != 1:
            print("atlas-splitter: nodo con varios atlas; conserva materiales importados", item["node_name"])
            continue
        obj.data.materials.clear()
        obj.data.materials.append(material_from_atlas(item["object_id"], atlas_paths[0], item["flip_v"]))
    if TARGET_OBJECT_ID is not None or TARGET_ATLAS_PATH is not None:
        kept_names = {item["node_name"] for item in selected}
        for name, obj in imported.items():
            if name not in kept_names:
                bpy.data.objects.remove(obj, do_unlink=True)
    if SEPARATE_LOOSE_PARTS:
        separate_loose_parts([obj for name, obj in imported.items() if name in kept_names])


if __name__ == "__main__":
    main()
"""


_SCRIPT_TEMPLATE = """# ruff: noqa
# Generated by atlas-splitter. Requires only Blender's built-in bpy API.
import json
from pathlib import Path

import bpy

SOURCE_GLB = __SOURCE_GLB__
UV_MANIFEST = __UV_MANIFEST__
ROOT_COLLECTION = "AtlasSplitter"


def local_path(path):
    if path.startswith("/mnt/") and len(path) > 6:
        return path[5].upper() + ":\\\\" + path[7:].replace("/", "\\\\")
    return path


def clean_previous_collection():
    collection = bpy.data.collections.get(ROOT_COLLECTION)
    if collection is not None:
        bpy.data.collections.remove(collection, do_unlink=True)


def make_root_collection():
    collection = bpy.data.collections.new(ROOT_COLLECTION)
    bpy.context.scene.collection.children.link(collection)
    return collection


def move_imported_objects(root, previous_objects):
    for obj in (item for item in bpy.context.scene.objects if item.name not in previous_objects):
        for collection in list(obj.users_collection):
            collection.objects.unlink(obj)
        root.objects.link(obj)


def image_node(nodes, links, image_path, socket):
    image = bpy.data.images.load(str(image_path), check_existing=True)
    node = nodes.new("ShaderNodeTexImage")
    node.image = image
    links.new(node.outputs["Color"], socket)
    return node


def apply_material(obj, element, output_root):
    files = element.get("exported_files", {})
    if not files:
        return
    material = bpy.data.materials.new(element["element_id"])
    material.use_nodes = True
    nodes, links = material.node_tree.nodes, material.node_tree.links
    principled = next(node for node in nodes if node.type == "BSDF_PRINCIPLED")
    if "baseColor" in files:
        image_node(nodes, links, output_root / files["baseColor"], principled.inputs["Base Color"])
    if "emissive" in files:
        image_node(nodes, links, output_root / files["emissive"], principled.inputs["Emission Color"])
    if "metallicRoughness" in files:
        node = image_node(nodes, links, output_root / files["metallicRoughness"], principled.inputs["Roughness"])
        links.new(node.outputs["Color"], principled.inputs["Metallic"])
    if "normal" in files:
        image = bpy.data.images.load(str(output_root / files["normal"]), check_existing=True)
        texture = nodes.new("ShaderNodeTexImage")
        texture.image = image
        normal = nodes.new("ShaderNodeNormalMap")
        links.new(texture.outputs["Color"], normal.inputs["Color"])
        links.new(normal.outputs["Normal"], principled.inputs["Normal"])
    obj.data.materials.clear()
    obj.data.materials.append(material)


def remap_uvs(obj, element):
    uvs = element.get("local_uvs")
    if not uvs or not obj.data.uv_layers:
        return
    layer = obj.data.uv_layers.active
    for loop, uv in zip(layer.data, uvs):
        loop.uv = uv


def main():
    manifest_path = Path(local_path(UV_MANIFEST))
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    if data.get("capabilities", {}).get("reconstruction_quality") != "geometry_guided":
        raise RuntimeError("El manifiesto no contiene geometría UV guiada.")
    clean_previous_collection()
    root = make_root_collection()
    previous_objects = {obj.name for obj in bpy.context.scene.objects}
    bpy.ops.import_scene.gltf(filepath=local_path(SOURCE_GLB))
    move_imported_objects(root, previous_objects)
    output_root = manifest_path.parent
    for element in data.get("elements", []):
        node_index = element.get("node_index")
        if node_index is None:
            continue
        candidates = [obj for obj in root.objects if obj.get("gltf_node_index") == node_index]
        for obj in candidates:
            remap_uvs(obj, element)
            apply_material(obj, element, output_root)


if __name__ == "__main__":
    main()
"""


_SEMANTIC_OBJECTS_SCRIPT_TEMPLATE = """# ruff: noqa
# Generated by atlas-splitter. Requires only Blender's built-in bpy API.
import json
from pathlib import Path

import bpy

SOURCE_GLB = __SOURCE_GLB__
SEMANTIC_MANIFEST = __SEMANTIC_MANIFEST__
ROOT_COLLECTION = "AtlasSplitterSemanticObjects"


def local_path(path):
    if path.startswith("/mnt/") and len(path) > 6:
        return path[5].upper() + ":\\\\" + path[7:].replace("/", "\\\\")
    return path


def clean_previous():
    collection = bpy.data.collections.get(ROOT_COLLECTION)
    if collection is not None:
        bpy.data.collections.remove(collection, do_unlink=True)


def separate_components(obj):
    bpy.ops.object.select_all(action="DESELECT")
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.mode_set(mode="EDIT")
    bpy.ops.mesh.separate(type="LOOSE")
    bpy.ops.object.mode_set(mode="OBJECT")
    return sorted(bpy.context.selected_objects, key=lambda item: item.name)


def main():
    data = json.loads(Path(local_path(SEMANTIC_MANIFEST)).read_text(encoding="utf-8"))
    clean_previous()
    root = bpy.data.collections.new(ROOT_COLLECTION)
    bpy.context.scene.collection.children.link(root)
    before = set(bpy.context.scene.objects)
    bpy.ops.import_scene.gltf(filepath=local_path(SOURCE_GLB))
    imported = [obj for obj in bpy.context.scene.objects if obj not in before]
    node_name = data["node"]["name"]
    target = next((obj for obj in imported if obj.name == node_name and obj.type == "MESH"), None)
    for obj in imported:
        if obj != target:
            bpy.data.objects.remove(obj, do_unlink=True)
    if target is None:
        raise RuntimeError("First_House_Baked no fue importado como malla.")
    components = separate_components(target)
    declared = data["components"]
    if len(components) != len(declared):
        raise RuntimeError("Los componentes sueltos importados no coinciden con el manifiesto; no se aplicaron grupos.")
    by_id = {}
    for component, item in zip(components, declared):
        component.name = item["component_id"]
        by_id[item["component_id"]] = component
    for group in data["groups"]:
        collection = bpy.data.collections.new(group["group_id"])
        root.children.link(collection)
        parent = bpy.data.objects.new(group["group_id"], None)
        parent.empty_display_type = "PLAIN_AXES"
        collection.objects.link(parent)
        for component_id in group["component_ids"]:
            component = by_id[component_id]
            for owner in list(component.users_collection):
                owner.objects.unlink(component)
            collection.objects.link(component)
            component.parent = parent


if __name__ == "__main__":
    main()
"""
